services:
  browserless:
    restart: always
    image: whatwewant/browserless:${SERVICE_BROWSERLESS_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_BROWSERLESS_PORT}:3000
    mem_limit: ${SERVICE_RESOURCE_LIMIT_MEM:-"8192m"}
    cpus: ${SERVICE_RESOURCE_LIMIT_CPUS:-4}

networks:
  default:
    external: true
    name: compose-ingress
